/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package modelNetGen;

import java.awt.Toolkit;
import java.util.HashSet;
import java.util.List;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.SwingWorker;

/**
 *
 * @author Libra
 */
public class ModelUI extends javax.swing.JFrame {

    /**
     * Creates new form ModelViewUI
     */
    public ModelUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modelGrp = new javax.swing.ButtonGroup();
        clusterGrp = new javax.swing.ButtonGroup();
        triQuadGrp = new javax.swing.ButtonGroup();
        ioTypeGrp = new javax.swing.ButtonGroup();
        ioGrp = new javax.swing.ButtonGroup();
        maxDistGrp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnInitModel = new javax.swing.JButton();
        btnStopModel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtGluFac = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGABAFac = new javax.swing.JTextField();
        chkDepolarGABA = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtIterFac = new javax.swing.JTextField();
        rdoRand = new javax.swing.JRadioButton();
        rdoBiDir = new javax.swing.JRadioButton();
        rdoUniDir = new javax.swing.JRadioButton();
        txtGenPairTIme = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnShow = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        txtNeuronNum = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtConnProb = new javax.swing.JTextField();
        txtWeightScale = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        chkWriteFile = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        btnCluster = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnCommNeiTest = new javax.swing.JButton();
        chkFwdGlu = new javax.swing.JCheckBox();
        chkRevGlu = new javax.swing.JCheckBox();
        rdoGlu = new javax.swing.JRadioButton();
        rdoGABA = new javax.swing.JRadioButton();
        rdoBoth = new javax.swing.JRadioButton();
        rdoTri = new javax.swing.JRadioButton();
        rdoQuad = new javax.swing.JRadioButton();
        txtGenGrpTime = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnSplit = new javax.swing.JButton();
        chkFreq = new javax.swing.JCheckBox();
        chkRepeat = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        rdoIOGlu = new javax.swing.JRadioButton();
        rdoGABAIO = new javax.swing.JRadioButton();
        rdoInput = new javax.swing.JRadioButton();
        rdoOutput = new javax.swing.JRadioButton();
        btnIODegree = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btnGlobalDegree = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPrg = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        prgBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnInitModel.setText("Init");
        btnInitModel.setPreferredSize(new java.awt.Dimension(85, 25));
        btnInitModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInitModelActionPerformed(evt);
            }
        });

        btnStopModel.setText("Stop");
        btnStopModel.setPreferredSize(new java.awt.Dimension(85, 25));
        btnStopModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopModelActionPerformed(evt);
            }
        });

        jLabel2.setText("Model Construct:");

        jLabel1.setText("Glu Factor ");

        txtGluFac.setEditable(false);
        txtGluFac.setText("1.0");
        txtGluFac.setPreferredSize(new java.awt.Dimension(40, 20));

        jLabel3.setText("GABA Factor");

        txtGABAFac.setEditable(false);
        txtGABAFac.setText("1.0");
        txtGABAFac.setPreferredSize(new java.awt.Dimension(40, 20));

        chkDepolarGABA.setSelected(true);
        chkDepolarGABA.setText("Depolar GABA");

        jLabel5.setText("Iteration Factor");

        txtIterFac.setText("1000");
        txtIterFac.setPreferredSize(new java.awt.Dimension(40, 20));
        txtIterFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIterFacActionPerformed(evt);
            }
        });

        modelGrp.add(rdoRand);
        rdoRand.setText("Random");
        rdoRand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoRandActionPerformed(evt);
            }
        });

        modelGrp.add(rdoBiDir);
        rdoBiDir.setText("ActiveBiDir");
        rdoBiDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoBiDirActionPerformed(evt);
            }
        });

        modelGrp.add(rdoUniDir);
        rdoUniDir.setSelected(true);
        rdoUniDir.setText("ActiveOutGoing");
        rdoUniDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoUniDirActionPerformed(evt);
            }
        });

        txtGenPairTIme.setText("2");
        txtGenPairTIme.setPreferredSize(new java.awt.Dimension(25, 20));
        txtGenPairTIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenPairTImeActionPerformed(evt);
            }
        });

        jLabel7.setText("s sampling");

        btnShow.setText("Show");
        btnShow.setEnabled(false);
        btnShow.setPreferredSize(new java.awt.Dimension(85, 25));
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        btnStart.setText("Start");
        btnStart.setPreferredSize(new java.awt.Dimension(85, 25));
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.setPreferredSize(new java.awt.Dimension(85, 25));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(10, 100));

        txtNeuronNum.setText("1000");
        txtNeuronNum.setPreferredSize(new java.awt.Dimension(40, 20));

        jLabel9.setText("Neurons");

        txtConnProb.setText("1.0");
        txtConnProb.setPreferredSize(new java.awt.Dimension(40, 20));

        txtWeightScale.setText("1.0");
        txtWeightScale.setPreferredSize(new java.awt.Dimension(40, 20));

        jLabel10.setText("Connection Prob Scale");

        jLabel11.setText("Syn Weight Scale");

        chkWriteFile.setSelected(true);
        chkWriteFile.setText("Write");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGluFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtGABAFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkDepolarGABA)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIterFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNeuronNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdoRand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoBiDir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoUniDir)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtWeightScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtConnProb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnInitModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnStopModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chkWriteFile))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtGenPairTIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGenPairTIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtConnProb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWeightScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInitModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStopModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkWriteFile))
                        .addGap(12, 12, 12))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNeuronNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoRand)
                            .addComponent(rdoBiDir)
                            .addComponent(rdoUniDir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(txtGluFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtGABAFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(chkDepolarGABA)
                            .addComponent(txtIterFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(62, 62, 62))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCluster.setText("Cluster");
        btnCluster.setPreferredSize(new java.awt.Dimension(85, 25));
        btnCluster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClusterActionPerformed(evt);
            }
        });

        jLabel4.setText("Common Neighbor:");

        btnCommNeiTest.setText("Test");
        btnCommNeiTest.setPreferredSize(new java.awt.Dimension(85, 25));
        btnCommNeiTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommNeiTestActionPerformed(evt);
            }
        });

        chkFwdGlu.setText("fwdGlu");

        chkRevGlu.setText("revGlu");

        clusterGrp.add(rdoGlu);
        rdoGlu.setText("Glu");

        clusterGrp.add(rdoGABA);
        rdoGABA.setText("GABA");

        clusterGrp.add(rdoBoth);
        rdoBoth.setSelected(true);
        rdoBoth.setText("Both");

        triQuadGrp.add(rdoTri);
        rdoTri.setSelected(true);
        rdoTri.setText("3");

        triQuadGrp.add(rdoQuad);
        rdoQuad.setText("4");

        txtGenGrpTime.setText("5");
        txtGenGrpTime.setPreferredSize(new java.awt.Dimension(25, 20));

        jLabel6.setText("s sampling");

        btnSplit.setText("Split");
        btnSplit.setPreferredSize(new java.awt.Dimension(85, 25));
        btnSplit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSplitActionPerformed(evt);
            }
        });

        chkFreq.setSelected(true);
        chkFreq.setText("Freq");

        chkRepeat.setSelected(true);
        chkRepeat.setText("Repeat x5");

        ioTypeGrp.add(rdoIOGlu);
        rdoIOGlu.setSelected(true);
        rdoIOGlu.setText("glutamate");

        ioTypeGrp.add(rdoGABAIO);
        rdoGABAIO.setText("GABA");

        ioGrp.add(rdoInput);
        rdoInput.setSelected(true);
        rdoInput.setText("Input");

        ioGrp.add(rdoOutput);
        rdoOutput.setText("Output");

        btnIODegree.setText("IO Deg");
        btnIODegree.setPreferredSize(new java.awt.Dimension(85, 25));
        btnIODegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIODegreeActionPerformed(evt);
            }
        });

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnGlobalDegree.setText("Degrees");
        btnGlobalDegree.setPreferredSize(new java.awt.Dimension(85, 28));
        btnGlobalDegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGlobalDegreeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCommNeiTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chkFwdGlu)
                        .addGap(18, 18, 18)
                        .addComponent(chkRevGlu)
                        .addGap(18, 18, 18)
                        .addComponent(txtGenGrpTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(rdoBoth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoGlu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoGABA)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCluster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rdoTri)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoQuad))
                            .addComponent(chkFreq)
                            .addComponent(chkRepeat)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSplit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                        .addComponent(jSeparator2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoIOGlu)
                            .addComponent(rdoInput))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoOutput)
                            .addComponent(rdoGABAIO)))
                    .addComponent(btnIODegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGlobalDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGlobalDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdoBoth)
                                    .addComponent(rdoGlu)
                                    .addComponent(rdoGABA)
                                    .addComponent(rdoTri)
                                    .addComponent(rdoQuad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCluster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkFreq))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSplit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkRepeat))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chkFwdGlu)
                                    .addComponent(chkRevGlu)
                                    .addComponent(txtGenGrpTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCommNeiTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdoIOGlu)
                                    .addComponent(rdoGABAIO))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdoInput)
                                    .addComponent(rdoOutput))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnIODegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtPrg.setColumns(20);
        txtPrg.setRows(5);
        jScrollPane1.setViewportView(txtPrg);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prgBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prgBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInitModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInitModelActionPerformed
        btnShow.setEnabled(false);
        pathToFile = FilesCommons.getDefaultFile();
        modelInitWorker().execute();
        btnInitModel.setEnabled(false);
    }//GEN-LAST:event_btnInitModelActionPerformed

    private void btnClusterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClusterActionPerformed
        clusterWorker().execute();
    }//GEN-LAST:event_btnClusterActionPerformed

    private void btnCommNeiTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommNeiTestActionPerformed
//        ModelProbe probe = new ModelProbe(m0);
        commNeiborWoker().execute();
    }//GEN-LAST:event_btnCommNeiTestActionPerformed

    private void btnStopModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopModelActionPerformed
        m0.setRunState(RunState.UserRequestStop);
    }//GEN-LAST:event_btnStopModelActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    }//GEN-LAST:event_formWindowClosed

    private void rdoRandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoRandActionPerformed
        modelType = ModelType.Ctrl;
//        circuitView.setNetworkType(modelType);
    }//GEN-LAST:event_rdoRandActionPerformed

    private void rdoBiDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBiDirActionPerformed
        modelType = ModelType.NetworkBiDir;
    }//GEN-LAST:event_rdoBiDirActionPerformed

    private void rdoUniDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoUniDirActionPerformed
        modelType = ModelType.Network;
    }//GEN-LAST:event_rdoUniDirActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        btnShow.setEnabled(false);
        displayModel();
    }//GEN-LAST:event_btnShowActionPerformed

    private void txtGenPairTImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenPairTImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenPairTImeActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        (new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                m0.setType(modelType);
                m0.setConnProbScale(Float.parseFloat(txtConnProb.getText()));
                m0.setWeightScale(Float.parseFloat(txtWeightScale.getText()));
                m0.setWriteFile(chkWriteFile.isSelected());
                m0.setDEPOLAR_GABA(chkDepolarGABA.isSelected());
                updateProgress();
                m0.genModelNetwork(pathToFile);
                return null;
            }
        }).execute();
        btnShow.setEnabled(true);
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        btnInitModel.setEnabled(true);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSplitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSplitActionPerformed
        split();      // TODO add your handling code here:
    }//GEN-LAST:event_btnSplitActionPerformed

    private void btnIODegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIODegreeActionPerformed
        ioDegreeWoker().execute();
    }//GEN-LAST:event_btnIODegreeActionPerformed

    private void btnGlobalDegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGlobalDegreeActionPerformed
        globalDegreeWorker().execute();
    }//GEN-LAST:event_btnGlobalDegreeActionPerformed

    private void txtIterFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIterFacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIterFacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ModelUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCluster;
    private javax.swing.JButton btnCommNeiTest;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGlobalDegree;
    private javax.swing.JButton btnIODegree;
    private javax.swing.JButton btnInitModel;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnSplit;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStopModel;
    private javax.swing.JCheckBox chkDepolarGABA;
    private javax.swing.JCheckBox chkFreq;
    private javax.swing.JCheckBox chkFwdGlu;
    private javax.swing.JCheckBox chkRepeat;
    private javax.swing.JCheckBox chkRevGlu;
    private javax.swing.JCheckBox chkWriteFile;
    private javax.swing.ButtonGroup clusterGrp;
    private javax.swing.ButtonGroup ioGrp;
    private javax.swing.ButtonGroup ioTypeGrp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.ButtonGroup maxDistGrp;
    private javax.swing.ButtonGroup modelGrp;
    private javax.swing.JProgressBar prgBar;
    private javax.swing.JRadioButton rdoBiDir;
    private javax.swing.JRadioButton rdoBoth;
    private javax.swing.JRadioButton rdoGABA;
    private javax.swing.JRadioButton rdoGABAIO;
    private javax.swing.JRadioButton rdoGlu;
    private javax.swing.JRadioButton rdoIOGlu;
    private javax.swing.JRadioButton rdoInput;
    private javax.swing.JRadioButton rdoOutput;
    private javax.swing.JRadioButton rdoQuad;
    private javax.swing.JRadioButton rdoRand;
    private javax.swing.JRadioButton rdoTri;
    private javax.swing.JRadioButton rdoUniDir;
    private javax.swing.ButtonGroup triQuadGrp;
    private javax.swing.JTextField txtConnProb;
    private javax.swing.JTextField txtGABAFac;
    private javax.swing.JTextField txtGenGrpTime;
    private javax.swing.JTextField txtGenPairTIme;
    private javax.swing.JTextField txtGluFac;
    private javax.swing.JTextField txtIterFac;
    private javax.swing.JTextField txtNeuronNum;
    private javax.swing.JTextArea txtPrg;
    private javax.swing.JTextField txtWeightScale;
    // End of variables declaration//GEN-END:variables

    private SwingWorker modelInitWorker() {
        SwingWorker calcWorker;
        calcWorker = new SwingWorker<Void, Void>() {
            @Override
            public Void doInBackground() {
                float gluFac = Float.parseFloat(txtGluFac.getText());
                float gabaFac = Float.parseFloat(txtGABAFac.getText());
                float iterFac = Float.parseFloat(txtIterFac.getText());
                //TODO need to test pathToFile exist
                m0 = new ModelNewN(gluFac, gabaFac, iterFac);
                updateProgress();
                int neuronNum = Integer.parseInt(txtNeuronNum.getText());
                m0.setCell(neuronNum, 8429, 0.76708864f);
                m0.init();
                return null;
            }
        };
        return calcWorker;
    }

    private void displayModel() {
        (new SwingWorker<Void, Void>() {
            @Override
            public Void doInBackground() {
//                System.out.println("model inited");
                circuitView = new CircuitViewUI();
                circuitView.setNetworkType(modelType);
                circuitView.setVisible(true);

                circuitView.setDim(m0.getDimension());
                circuitView.setCellList(m0.getCellList());
//                circuitView.setMyWorker(this);

                final ScheduledExecutorService ses = Executors.newScheduledThreadPool(1);
                final Runnable displayUpdate = new Runnable() {
                    @Override
                    public void run() {
                        if (!circuitView.isVisible()) {
                            btnShow.setEnabled(true);
                            ses.shutdown();
                        }
                        if (m0.getRunState() == RunState.GeneratingNet) {
                            circuitView.setConnected(new HashSet<>(m0.getConnected()));
                            circuitView.repaintCanvas();
                        }

                        if (m0.getRunState() == RunState.NetGenerated) {
                            circuitView.setConnected(new HashSet<>(m0.getConnected()));
                            circuitView.repaintCanvas();
                            ses.shutdown();
                        }
                    }
                };
                ses.scheduleWithFixedDelay(displayUpdate, 1, 1, TimeUnit.SECONDS);
                return null;
            }
        }).execute();
    }

    private SwingWorker clusterWorker() {
        SwingWorker clusterWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() {
                int type = rdoBoth.isSelected() ? 0 : rdoGlu.isSelected() ? 1 : 2;
                int size = rdoTri.isSelected() ? 3 : 4;
                int repeat = chkRepeat.isSelected() ? 5 : 1;

                while (repeat > 0) {
                    int[] histo = m0.probeCluster(Integer.parseInt(txtGenGrpTime.getText()), type, size);
//                D.tp("TYPE " + type + ", " + Arrays.toString(histo));
                    System.out.print(modelType + "\tTYPE_" + type + "\tGABA_" + (chkDepolarGABA.isSelected() ? "Depolar" : "HyperPolar"));
                    System.out.print("\t");
                    if (chkFreq.isSelected()) {
                        int total = 0;
                        for (int i = 0; i < histo.length; i++) {
                            total += histo[i];
                        }
                        for (int i = 0; i < histo.length; i++) {
                            System.out.print((double) histo[i] / total);
                            System.out.print("\t");
                        }
                    } else {
                        for (int i = 0; i < histo.length; i++) {
                            System.out.print(histo[i]);
                        }
                    }
                    System.out.println();
                    repeat--;
                }
                split();
                return null;
            }
        };
        return clusterWorker;
    }

    private SwingWorker commNeiborWoker() {
        SwingWorker commNeiborWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() {
                int repeat = chkRepeat.isSelected() ? 5 : 1;
                while (repeat > 0) {
                    m0.probeCommNeib(
                            Integer.parseInt(txtGenGrpTime.getText()),
                            chkFwdGlu.isSelected(), chkRevGlu.isSelected());
                    repeat--;
                }
                split();
                return null;
            }
        };
        return commNeiborWorker;
    }

    private SwingWorker ioDegreeWoker() {
        SwingWorker ioWorker;
        ioWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() {
                int repeat = chkRepeat.isSelected() ? 5 : 1;
                while (repeat > 0) {
                    int[] degrees = m0.probeIO(
                            Integer.parseInt(txtGenGrpTime.getText()),
                            rdoIOGlu.isSelected(), rdoInput.isSelected());

                    System.out.println((rdoInput.isSelected() ? "Input" : "output") + "\t"
                            + (rdoIOGlu.isSelected() ? "Glu" : "GABA"));
                    if (chkFreq.isSelected()) {
                        int total = 0;
                        for (int i = 0; i < degrees.length; i++) {
                            total += degrees[i];
                        }
                        for (int i = 0; i < degrees.length; i++) {
                            System.out.print((double) degrees[i] / total);
                            System.out.print("\t");
                        }
                    } else {
                        for (int i = 0; i < degrees.length; i++) {
                            System.out.print(degrees[i]);
                            System.out.print("\t");
                        }
                    }
                    System.out.println();
                    repeat--;
                }
                split();
                return null;
            }
        };
        return ioWorker;
    }

    private SwingWorker globalDegreeWorker() {
        SwingWorker globalDegreeWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() {
                m0.probeGlobalDegrees();
                split();
                return null;
            }
        };
        return globalDegreeWorker;
    }

    private void split() {
        System.out.println("===========================================");
        Toolkit.getDefaultToolkit().beep();
    }

    private void updateProgress() {
        if (updating) {
            return;
        }
        updating = true;
        final ScheduledExecutorService ses = Executors.newSingleThreadScheduledExecutor();
        Runnable progressUpdater = new Runnable() {
            @Override
            public void run() {

                List<String> updates = m0.getUpdates();
                txtPrg.setText("");
                for (int i = 0; i < updates.size(); i++) {
                    String s = updates.get(i) + "\r\n";
                    txtPrg.append(s);
//                    System.out.println(m0.getProgress());
                    prgBar.setValue(m0.getProgress());
                }
                if (m0.getRunState() == RunState.StoppedByUser || m0.getRunState() == RunState.NetGenerated) {
                    ses.shutdown();
                    prgBar.setValue(0);
                    updating = false;
                }
            }
        };
        ses.scheduleWithFixedDelay(progressUpdater, 1, 1, TimeUnit.SECONDS);
    }
    private ModelNewN m0;
    private CircuitViewUI circuitView;
    private String pathToFile;
    private ModelType modelType = ModelType.Network;
    private boolean updating = false;
}
